services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./main/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./main/package.json
        - action: rebuild
          path: ./main/Dockerfile
        - action: sync
          path: ./common
          target: /app
        - action: sync
          path: ./main
          target: /app
          ignore:
            - node_modules/
            - Dockerfile
            - package.json
            - README.md
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  manager:
    container_name: manager
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./manager/package.json
        - action: rebuild
          path: ./manager/Dockerfile
        - action: sync
          path: ./common
          target: /app
        - action: sync
          path: ./manager
          target: /app
          ignore:
            - node_modules/
            - Dockerfile
            - package.json
            - README.md
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true